name: Generate Pokemon

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ab-smith/pokemon-readme-action@main
        with:
          github_user: codemaster321
